-- MySQL Script generated by MySQL Workbench
-- 07/15/15 20:21:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MifotoConChanito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MifotoConChanito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MifotoConChanito` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MifotoConChanito` ;

-- -----------------------------------------------------
-- Table `MifotoConChanito`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MifotoConChanito`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `a_Paterno` VARCHAR(45) NULL,
  `a_Materno` VARCHAR(45) NULL,
  `user` VARCHAR(15) NULL,
  `password` VARCHAR(10) NULL,
  `tipoUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MifotoConChanito`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MifotoConChanito`.`municipios` (
  `id_m` INT NOT NULL AUTO_INCREMENT,
  `nombre_Municipio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_m`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MifotoConChanito`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MifotoConChanito`.`fotos` (
  `id_f` INT NOT NULL AUTO_INCREMENT,
  `tituloImagen` VARCHAR(45) NULL,
  `fecha_evento` DATE NULL,
  `localidadColonia` VARCHAR(45) NULL,
  `descripcion_Evento` VARCHAR(60) NULL,
  `img_Evento` VARCHAR(150) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `municipios_id_m` INT NOT NULL,
  PRIMARY KEY (`id_f`, `Usuarios_idUsuarios`, `municipios_id_m`),
  INDEX `fk_fotos_Usuarios_idx` (`Usuarios_idUsuarios` ASC),
  INDEX `fk_fotos_municipios1_idx` (`municipios_id_m` ASC),
  CONSTRAINT `fk_fotos_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `MifotoConChanito`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fotos_municipios1`
    FOREIGN KEY (`municipios_id_m`)
    REFERENCES `MifotoConChanito`.`municipios` (`id_m`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
